name: Deploy to AWS Lambda via Zappa

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      PYTHON_VERSION: '3.10'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create venv & install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install zappa

      - name: Configure AWS credentials (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy (or update) with Zappa
        run: |
          . .venv/bin/activate
          # Ensure S3 bucket exists (idempotent)
          aws s3api head-bucket --bucket nestle-sentiment-zappa-deploy 2>/dev/null || aws s3 mb s3://nestle-sentiment-zappa-deploy --region $AWS_DEFAULT_REGION
          zappa update dev --settings_file zappa_settings.json || zappa deploy dev --settings_file zappa_settings.json


